### ISSUE TITLE
Support to define filepaths

### ISSUE THREAD

**Issue by pudgereyem** [novwhisky/Edge-Animate-Runtime#3]
Hi @wittnl,
what is the status of this github repository? Do you use it for development, or is it more like a mirror?
## Background

I'm developing a site on WordPress, and when using WordPress all assets are stored inside the theme folder, e.g; my-awesome-theme/assets/.
## The problem

Adobe Edge Animate only works when you're in the actual root of the site, since it uses relative url:s to load resources. Resulting in 404's and no animations. I think it would be useful if you could configure the paths, when calling `loadComposition`. 
## Possible solution

What do you think about the option to define the paths for the different kind of resources. See below.

```
<script>
    AdobeEdge.loadComposition('animation_name', 'EDGE-1337', {
        paths: {
            images: '/wp-content/themes/my-awesome-theme/assets/edge/animation_name/images/',
            javascript: '/wp-content/themes/my-awesome-theme/assets/edge/animation_name/javascript/',
            audio: '/wp-content/themes/my-awesome-theme/assets/edge/animation_name/audio/',
            video: '/wp-content/themes/my-awesome-theme/assets/edge/animation_name/video/',
        },
        scaleToFit: "width",
        centerStage: "none",
        minW: "0px",
        maxW: "undefined",
        width: "826px",
        height: "620px",
        bScaleToParent:true
    }, {"dom":{}}, {"dom":{}});
</script>
```

**Comment by novwhisky** [comment]
Hi @pudgereyem, thanks for reaching out. This is effectively a mirror for providing easy access to package managers. Unfortunately my only connection to Adobe is the credit card they draw funds from every month, but I can recall having problems like the ones you describe. At that time I was able to hand-edit the preloader config to make my assets relative URLs, but I honestly haven't seen what's changed in the latest version.

Hope this info is helpful and good luck!

**Comment by pudgereyem** [comment]
Hi @wittnl.
Okay, I see.

Regarding the problems I encountered I did write about how I solved it.
- [Getting Adobe Edge Animations to work in WordPress](http://codepen.io/pudgereyem/blog/getting-adobe-edge-animations-to-work-in-wordpress)
- [Making Adobe Edge Animations responsive](http://codepen.io/pudgereyem/blog/making-adobe-edge-animations-responsive)

..and you can see all this in action over at http://site.quizup.com/jobs/
